# Rolling nightly channel pointer — auto-generated by .github/workflows/nightly.yml.
#
# This file lives on the `nightly` git ref. The hashes and version below
# match the artifacts published in the current rolling nightly release.
# This file is NOT present on `main` with real hashes — always consume via
# the `nightly` ref:
#
#   nix run github:0xErwin1/dbflux/nightly#dbflux-nightly
#
# From-source nightly (no hash needed):
#
#   nix run github:0xErwin1/dbflux/nightly#dbflux-source
{
  version = "0.9.0-nightly+d6dbffe";

  artifacts = {
    "x86_64-linux" = {
      url = "https://github.com/0xErwin1/dbflux/releases/download/nightly/dbflux-linux-amd64.tar.gz";
      hash = "sha256-9ajvzK5jTIo2EXZKZyK+JWPdYq3SL6ndlUSkEmd56J0=";
    };
    "aarch64-linux" = {
      url = "https://github.com/0xErwin1/dbflux/releases/download/nightly/dbflux-linux-arm64.tar.gz";
      hash = "sha256-Mb09J/U0uobDf5K2C3bCwt7B81JMoaDO8NC94BVo+pM=";
    };
  };
}
