use crate::query::generator::{SelectQuery, build_select_query};
use crate::query::visual_query::VisualQuerySpec;
use crate::sql::dialect::SqlDialect;

/// Wraps the SELECT generated from `spec` in a `COUNT(*)` outer query.
///
/// The inner SELECT is generated byte-for-byte identically to the data-fetch
/// query, so the count is always consistent with the row result.
///
/// All dialects supported by DBFlux accept `SELECT COUNT(*) FROM (<select>) AS x`
/// syntax, so no dialect-specific branching is needed here.
pub fn count_query_from_spec(spec: &VisualQuerySpec, dialect: &dyn SqlDialect) -> SelectQuery {
    // The public signature returns `SelectQuery` with no error channel, and
    // `build_select_query` is deterministic per `(spec, dialect)`: supported
    // callers pass a `RelationalLowering.spec` whose SELECT already built
    // successfully (or rebuild the identical spec), so the `Err` arm is not
    // reachable for them. A hand-built invalid spec (e.g. `IN` without a list
    // value) would still panic here; narrowing the return type to `Result`
    // would be a public-API break for `dbflux_core::count_query_from_spec`.
    #[expect(
        clippy::expect_used,
        reason = "public API returns SelectQuery by value; Err unreachable for lowering specs"
    )]
    let inner =
        build_select_query(spec, dialect).expect("spec must be valid when entering count path");

    SelectQuery {
        sql: format!("SELECT COUNT(*) FROM ({}) AS dbflux_count_subq", inner.sql),
        params: inner.params,
    }
}

/// Wraps a single read statement typed by the user in a `COUNT(*)` outer
/// query, so the total row count is known without fetching the rows.
///
/// Statement terminators are dropped wherever they sit, including before a
/// trailing comment, and the statement sits on its own lines so a trailing
/// `--` comment cannot swallow the closing parenthesis.
pub fn count_query_from_sql(sql: &str) -> String {
    let statement = crate::driver::capabilities::sql_statement_ranges(sql)
        .into_iter()
        .filter_map(|range| sql.get(range).map(str::trim))
        .filter(|segment| !segment.is_empty())
        .collect::<Vec<_>>()
        .join("\n");
    format!("SELECT COUNT(*) FROM (\n{statement}\n) AS dbflux_count_subq")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn count_query_from_sql_strips_semicolons_and_isolates_comments() {
        assert_eq!(
            count_query_from_sql("  SELECT * FROM users -- all ;\n ; \n"),
            "SELECT COUNT(*) FROM (\nSELECT * FROM users -- all ;\n) AS dbflux_count_subq"
        );
        assert_eq!(
            count_query_from_sql("SELECT * FROM users; -- note"),
            "SELECT COUNT(*) FROM (\nSELECT * FROM users\n-- note\n) AS dbflux_count_subq"
        );
    }
    use crate::query::visual_query::{
        Comparator, FilterNode, JoinKind, JoinOn, JoinStep, LiteralValue, Predicate,
        PredicateValue, Projection, SourceTable, VisualQuerySpec,
    };
    use crate::sql::dialect::{DefaultSqlDialect, PlaceholderStyle, SqlDialect};

    fn simple_spec(table: &str) -> VisualQuerySpec {
        VisualQuerySpec {
            source: SourceTable {
                schema: None,
                table: table.to_string(),
                alias: table.to_string(),
            },
            projection: Projection::All,
            joins: vec![],
            filter: None,
            group_by: vec![],
            aggregates: vec![],
            having: None,
            sort: vec![],
            limit: None,
            offset: 0,
        }
    }

    fn spec_with_join(from_table: &str, to_table: &str) -> VisualQuerySpec {
        let mut spec = simple_spec(from_table);
        spec.joins = vec![JoinStep {
            kind: JoinKind::Inner,
            from_alias: from_table.to_string(),
            to_schema: None,
            to_table: to_table.to_string(),
            to_alias: to_table.to_string(),
            on: JoinOn::FkPath {
                from_column: "id".to_string(),
                to_column: "user_id".to_string(),
            },
        }];
        spec.filter = Some(FilterNode::Predicate(Predicate {
            source_alias: to_table.to_string(),
            column: "email".to_string(),
            comparator: Comparator::Eq,
            value: PredicateValue::Single(LiteralValue::Text("alice@example.com".to_string())),
            node_id: 0,
        }));
        spec
    }

    // T20: count query wraps inner select
    #[test]
    fn count_query_wraps_inner_select() {
        let spec = spec_with_join("posts", "users");
        let result = count_query_from_spec(&spec, &DefaultSqlDialect);

        assert!(
            result.sql.starts_with("SELECT COUNT(*) FROM ("),
            "must wrap in COUNT(*) outer query, got: {}",
            result.sql
        );
        assert!(
            result.sql.ends_with(") AS dbflux_count_subq"),
            "must end with subquery alias, got: {}",
            result.sql
        );
        assert_eq!(result.params.len(), 1, "params must be forwarded unchanged");
    }

    #[test]
    fn count_query_params_are_forwarded() {
        let spec = spec_with_join("posts", "users");
        let inner = build_select_query(&spec, &DefaultSqlDialect).unwrap();
        let count = count_query_from_spec(&spec, &DefaultSqlDialect);

        assert_eq!(
            inner.params, count.params,
            "params must be identical between inner SELECT and COUNT wrapper"
        );
    }

    #[test]
    fn count_query_sqlite_dialect_valid_syntax() {
        struct SqliteDialect;
        impl SqlDialect for SqliteDialect {
            fn quote_identifier(&self, name: &str) -> String {
                format!("\"{}\"", name)
            }
            fn qualified_table(&self, _schema: Option<&str>, table: &str) -> String {
                format!("\"{}\"", table)
            }
            fn value_to_literal(&self, v: &crate::Value) -> String {
                DefaultSqlDialect.value_to_literal(v)
            }
            fn escape_string(&self, s: &str) -> String {
                s.replace('\'', "''")
            }
            fn placeholder_style(&self) -> PlaceholderStyle {
                PlaceholderStyle::QuestionMark
            }
        }

        let spec = simple_spec("events");
        let result = count_query_from_spec(&spec, &SqliteDialect);

        assert!(
            result.sql.contains("SELECT COUNT(*) FROM"),
            "SQLite dialect count query must contain COUNT(*), got: {}",
            result.sql
        );
        assert!(
            result.sql.contains("dbflux_count_subq"),
            "subquery alias must be present, got: {}",
            result.sql
        );
    }
}
